/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassObjets;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CDI305
 */
public class JFAjoutContact extends javax.swing.JFrame {

    /**
     * Creates new form JFAjoutContact
     */
    public JFAjoutContact() {
        initComponents();
    }

    Console maConsole = new Console();
    JFSuppContacts jfsupp = new JFSuppContacts();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioAmis = new javax.swing.JRadioButton();
        jRadioConnaissance = new javax.swing.JRadioButton();
        jRadioFamille = new javax.swing.JRadioButton();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jTextPrenom = new javax.swing.JTextField();
        jLabelTelephone = new javax.swing.JLabel();
        jTextTelephone = new javax.swing.JTextField();
        jLabelAdresse = new javax.swing.JLabel();
        jTextAdresse = new javax.swing.JTextField();
        jLabelCodePostal = new javax.swing.JLabel();
        jTextCodePostal = new javax.swing.JTextField();
        jLabelVille = new javax.swing.JLabel();
        jLabelTelMobile = new javax.swing.JLabel();
        jTextTelMobile = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jTextMail = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jTextNom = new javax.swing.JTextField();
        jTextVille = new javax.swing.JTextField();
        jLabelDateNaissance = new javax.swing.JLabel();
        jTextDateNaissance = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix de l'ajout du contact"));
        jPanel1.setLayout(null);

        jLabel1.setText("Que souhaitez vous ajouter :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 180, 40);

        buttonGroup1.add(jRadioAmis);
        jRadioAmis.setText("Amis");
        jRadioAmis.setToolTipText("Nom, Prenom, Telephone, Adresse, Email, Telephone Portable");
        jRadioAmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAmisActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioAmis);
        jRadioAmis.setBounds(20, 90, 60, 30);

        buttonGroup1.add(jRadioConnaissance);
        jRadioConnaissance.setText("Connaissance");
        jRadioConnaissance.setToolTipText("Nom, Prenom, Telephone, Adresse, Email");
        jRadioConnaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioConnaissanceActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioConnaissance);
        jRadioConnaissance.setBounds(20, 60, 110, 30);

        buttonGroup1.add(jRadioFamille);
        jRadioFamille.setText("Famille");
        jRadioFamille.setToolTipText("Nom, Prenom, Telephone, Adresse, Email, Telephone Portable, Date de Naissance");
        jRadioFamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFamilleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioFamille);
        jRadioFamille.setBounds(20, 130, 130, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 230, 250);

        jLabelNom.setText("Nom :");
        getContentPane().add(jLabelNom);
        jLabelNom.setBounds(280, 20, 40, 30);

        jLabelPrenom.setText("Prenom :");
        getContentPane().add(jLabelPrenom);
        jLabelPrenom.setBounds(550, 20, 50, 30);

        jTextPrenom.setToolTipText("Indiquez votre prenom (obligatoire)");
        jTextPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrenomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPrenom);
        jTextPrenom.setBounds(550, 50, 170, 30);

        jLabelTelephone.setText("Telephone :");
        getContentPane().add(jLabelTelephone);
        jLabelTelephone.setBounds(280, 80, 90, 40);

        jTextTelephone.setToolTipText("Indiquez votre telephone (obligatoire)");
        jTextTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelephoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTelephone);
        jTextTelephone.setBounds(280, 110, 170, 30);

        jLabelAdresse.setText("Adresse :");
        getContentPane().add(jLabelAdresse);
        jLabelAdresse.setBounds(550, 80, 60, 30);

        jTextAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAdresseActionPerformed(evt);
            }
        });
        getContentPane().add(jTextAdresse);
        jTextAdresse.setBounds(550, 110, 170, 30);

        jLabelCodePostal.setText("Code postal : ");
        getContentPane().add(jLabelCodePostal);
        jLabelCodePostal.setBounds(280, 150, 110, 30);

        jTextCodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodePostalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCodePostal);
        jTextCodePostal.setBounds(280, 180, 170, 30);

        jLabelVille.setText("Ville : ");
        getContentPane().add(jLabelVille);
        jLabelVille.setBounds(550, 150, 60, 20);

        jLabelTelMobile.setText("Telephone mobile :");
        getContentPane().add(jLabelTelMobile);
        jLabelTelMobile.setBounds(550, 220, 130, 30);

        jTextTelMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelMobileActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTelMobile);
        jTextTelMobile.setBounds(550, 250, 170, 30);

        jLabelMail.setText("Adresse Mail :");
        getContentPane().add(jLabelMail);
        jLabelMail.setBounds(280, 220, 110, 30);

        jTextMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextMail);
        jTextMail.setBounds(280, 250, 170, 30);

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAjouter);
        jButtonAjouter.setBounds(560, 330, 130, 30);

        jTextNom.setToolTipText("Indiquez votre nom (obligatoire)");
        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNom);
        jTextNom.setBounds(280, 50, 170, 30);

        jTextVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVilleActionPerformed(evt);
            }
        });
        getContentPane().add(jTextVille);
        jTextVille.setBounds(550, 180, 170, 30);

        jLabelDateNaissance.setText("Date de naissance :");
        getContentPane().add(jLabelDateNaissance);
        jLabelDateNaissance.setBounds(280, 290, 120, 30);

        jTextDateNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDateNaissanceActionPerformed(evt);
            }
        });
        getContentPane().add(jTextDateNaissance);
        jTextDateNaissance.setBounds(280, 330, 170, 30);

        setSize(new java.awt.Dimension(781, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioConnaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioConnaissanceActionPerformed
        // TODO add your handling code here:
        jTextTelMobile.setVisible(false);
        jLabelTelMobile.setVisible(false);
        jTextDateNaissance.setVisible(false);
        jLabelDateNaissance.setVisible(false);
    }//GEN-LAST:event_jRadioConnaissanceActionPerformed

    private void jRadioAmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAmisActionPerformed
        // TODO add your handling code here:
        jTextTelMobile.setVisible(true);
        jLabelTelMobile.setVisible(true);
        jTextDateNaissance.setVisible(false);
        jLabelDateNaissance.setVisible(false);
    }//GEN-LAST:event_jRadioAmisActionPerformed

    private void jRadioFamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFamilleActionPerformed
        // TODO add your handling code here:
        jTextTelMobile.setVisible(true);
        jLabelTelMobile.setVisible(true);
        jTextDateNaissance.setVisible(true);
        jLabelDateNaissance.setVisible(true);
    }//GEN-LAST:event_jRadioFamilleActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jTextPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrenomActionPerformed

    private void jTextTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelephoneActionPerformed

    private void jTextAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAdresseActionPerformed

    private void jTextCodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodePostalActionPerformed

    private void jTextVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVilleActionPerformed

    private void jTextTelMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelMobileActionPerformed

    private void jTextMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMailActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showInternalMessageDialog(null, "Oops:ClassNotFound :"+ex.getMessage(), "creation Driver", JOptionPane.ERROR_MESSAGE);
//            System.err.println("Oops:ClassNotFound:" + ex.getMessage());
        }

        Connection connexion = null;

        try {
            String url = "jdbc:sqlserver://localhost:1433;"
                    + "databaseName=CarnetAdresse;user=sa;password=sa";

            connexion = DriverManager.getConnection(url);
        } catch (SQLException ex) {
            JOptionPane.showInternalMessageDialog(null, "Oops:Connect :"+ex.getErrorCode(), "Connexion au serveur", JOptionPane.ERROR_MESSAGE);
//            System.err.println("Oops:Connect:" + ex.getErrorCode()
//                    + "/" + ex.getMessage());
            return;
        }

        try {
            Statement stmt = connexion.createStatement();

            String nom = jTextNom.getText();
            String prenom = jTextPrenom.getText();
            String telephone = jTextTelephone.getText();
            String adresseRue = jTextAdresse.getText();
            String codePostal = jTextCodePostal.getText();
            String ville = jTextVille.getText();
            String email = jTextMail.getText();
            String telephonePortable = "";
            String typeContact = "1";
            if (jRadioAmis.isSelected() || jRadioFamille.isSelected()) {
                telephonePortable = jTextTelMobile.getText();
                typeContact = "2";
            }
            String dateNaissance = "";
            if (jRadioFamille.isSelected()) {
                dateNaissance = jTextDateNaissance.getText();
                typeContact = "3";
            }
            String query = "INSERT INTO CarnetAdresse VALUES "
                    + "('" + nom + "','" + prenom + "','" + telephone + "','" + adresseRue + "','" + codePostal + "','" + ville + "','" + email + "','" + typeContact
                    + "','" + telephonePortable
                    + "','" + dateNaissance + "')";
            stmt.executeUpdate(query);
        } catch (SQLException ex) {
            JOptionPane.showInternalMessageDialog(null, "Oops: nouvContact" + ex.getMessage(), "Ajout nouveau Contact", JOptionPane.ERROR_MESSAGE);
//            System.err.println("Erreur nouvContact" + ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Contact ajouté", "Ajout d'un contact", JOptionPane.PLAIN_MESSAGE);
        jfsupp.synchroCarnet();
        nettoyage();
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    
    private void jTextDateNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDateNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDateNaissanceActionPerformed

    public void nettoyage() {
        jTextNom.setText("");
        jTextPrenom.setText("");
        jTextTelephone.setText("");
        jTextAdresse.setText("");
        jTextCodePostal.setText("");
        jTextVille.setText("");
        jTextMail.setText("");
        jTextTelMobile.setText("");
        jTextDateNaissance.setText("");
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelCodePostal;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelTelMobile;
    private javax.swing.JLabel jLabelTelephone;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioAmis;
    private javax.swing.JRadioButton jRadioConnaissance;
    private javax.swing.JRadioButton jRadioFamille;
    private javax.swing.JTextField jTextAdresse;
    private javax.swing.JTextField jTextCodePostal;
    private javax.swing.JTextField jTextDateNaissance;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.JTextField jTextTelMobile;
    private javax.swing.JTextField jTextTelephone;
    private javax.swing.JTextField jTextVille;
    // End of variables declaration//GEN-END:variables
}
